# Generated by Django 5.0.6 on 2026-05-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_retailer_created_by_user_created_by"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("branches", "0002_branch_created_by"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["timestamp"], name="accounts_au_timesta_276167_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginlog",
            index=models.Index(
                fields=["login_time"], name="accounts_lo_login_t_02ac71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active"], name="accounts_us_is_acti_a5841d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["retailer", "branch"], name="accounts_us_retaile_b633c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["retailer", "role"], name="accounts_us_retaile_a1190d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["retailer", "is_active"], name="accounts_us_retaile_4d389c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["refresh_token"], name="accounts_us_refresh_c11c5b_idx"
            ),
        ),
    ]
