# Generated by Django 5.0.6 on 2026-05-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_retailer_alter_user_options_loginlog_branch_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('branches', '0002_branch_retailer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['retailer'], name='accounts_au_retaile_a91443_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['retailer'], name='accounts_lo_retaile_ce2984_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['branch'], name='accounts_lo_branch__c20786_idx'),
        ),
        migrations.AddIndex(
            model_name='retailer',
            index=models.Index(fields=['name'], name='accounts_re_name_66b7fd_idx'),
        ),
        migrations.AddIndex(
            model_name='retailer',
            index=models.Index(fields=['mobile'], name='accounts_re_mobile_89becb_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['retailer'], name='accounts_us_retaile_a10baa_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['branch'], name='accounts_us_branch__21b572_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['retailer'], name='accounts_us_retaile_9b5a65_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['branch'], name='accounts_us_branch__1e75f0_idx'),
        ),
    ]
