# Generated by Django 5.0.6 on 2026-06-05 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auditlog_accounts_au_timesta_276167_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='accounts_em_user_id_eb881a_idx'), models.Index(fields=['otp'], name='accounts_em_otp_f89c28_idx'), models.Index(fields=['is_verified'], name='accounts_em_is_veri_7a5656_idx'), models.Index(fields=['expires_at'], name='accounts_em_expires_2be763_idx'), models.Index(fields=['user', 'otp', 'is_verified'], name='accounts_em_user_id_beaa54_idx')],
            },
        ),
    ]
