# Generated by Django 5.0.6 on 2026-06-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
