from .expiry_damage_urls import *
from .payment_urls import *
from .purchase_return_urls import *
from .receipt_urls import *
from .sales_urls import *
from .sales_return_urls import *
from .stock_adjustment_urls import *
from .stock_batch_urls import *
from .stock_transaction_urls import *
from .stock_transfer_urls import *