from .sales_report_urls import *
from .sales_return_report_urls import *
from .purchase_report_urls import *
from .purchase_return_report_urls import *
from .stock_report_urls import *
from .expiry_report_urls import *
from .low_stock_report_urls import *
from .product_ledger_urls import *
from .supplier_ledger_urls import *
from .customer_ledger_urls import *
from .profit_loss_urls import *
from .dashboard_urls import *
from .analytics_urls import *
from .gst_report_urls import *
from .payment_report_urls import *
from .receipt_report_urls import *
from .stock_transfer_report_urls import *
from .stock_adjustment_report_urls import *