# Generated by Django 5.0.6 on 2026-05-28 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_auditlog_accounts_au_timesta_276167_idx_and_more"),
        ("branches", "0003_branch_branches_br_retaile_5e3433_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_years",
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_years",
                        to="accounts.retailer",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["retailer"], name="settings_fi_retaile_d4591c_idx"
                    ),
                    models.Index(
                        fields=["branch"], name="settings_fi_branch__04576d_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="settings_fi_is_acti_15f992_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="settings_fi_start_d_5c97da_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="settings_fi_end_dat_10e055_idx"
                    ),
                    models.Index(
                        fields=["retailer", "branch"],
                        name="settings_fi_retaile_a94ee9_idx",
                    ),
                ],
                "unique_together": {("retailer", "name")},
            },
        ),
        migrations.CreateModel(
            name="GeneralSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=100)),
                ("low_stock_limit", models.PositiveIntegerField(default=10)),
                ("enable_gst", models.BooleanField(default=True)),
                ("enable_barcode", models.BooleanField(default=True)),
                ("enable_expiry_alert", models.BooleanField(default=True)),
                ("enable_loose_sale", models.BooleanField(default=True)),
                ("enable_negative_stock", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retailer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_setting",
                        to="accounts.retailer",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["retailer"], name="settings_ge_retaile_055109_idx"
                    )
                ],
            },
        ),
    ]
