# Generated by Django 5.0.6 on 2026-05-14 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='masters_cat_name_8bf495_idx'), models.Index(fields=['code'], name='masters_cat_code_9423e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='masters_man_name_db867b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('strength', models.CharField(blank=True, help_text='Example: 500mg, 650mg', max_length=100, null=True)),
                ('units_per_strip', models.PositiveIntegerField(default=1, help_text='Example: 10 tablets in 1 strip')),
                ('loose_sale_allowed', models.BooleanField(default=True)),
                ('prescription_required', models.BooleanField(default=False)),
                ('rack_no', models.CharField(blank=True, max_length=50, null=True)),
                ('minimum_stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='masters.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='masters.manufacturer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('offer_type', models.CharField(choices=[('PRODUCT_DISCOUNT', 'Product Discount'), ('CATEGORY_DISCOUNT', 'Category Discount'), ('BUY_X_GET_Y', 'Buy X Get Y'), ('QUANTITY_DISCOUNT', 'Quantity Discount'), ('FLAT_DISCOUNT', 'Flat Discount'), ('BILL_AMOUNT_DISCOUNT', 'Bill Amount Discount'), ('MANUFACTURER_DISCOUNT', 'Manufacturer Discount'), ('EXPIRY_CLEARANCE', 'Expiry Clearance'), ('FESTIVAL_OFFER', 'Festival Offer'), ('MEMBER_DISCOUNT', 'Member Discount')], max_length=30)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat')], default='PERCENTAGE', max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('flat_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buy_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('free_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry_before_days', models.PositiveIntegerField(blank=True, null=True)),
                ('member_type', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='masters.category')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='masters.manufacturer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='masters.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('drug_license_no', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(related_name='suppliers', to='branches.branch')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='masters_pro_name_7c9c1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'manufacturer', 'strength')},
        ),
        migrations.AddIndex(
            model_name='salesoffer',
            index=models.Index(fields=['offer_type'], name='masters_sal_offer_t_b37d24_idx'),
        ),
        migrations.AddIndex(
            model_name='salesoffer',
            index=models.Index(fields=['start_date'], name='masters_sal_start_d_34670b_idx'),
        ),
        migrations.AddIndex(
            model_name='salesoffer',
            index=models.Index(fields=['end_date'], name='masters_sal_end_dat_ec3aac_idx'),
        ),
        migrations.AddIndex(
            model_name='salesoffer',
            index=models.Index(fields=['is_active'], name='masters_sal_is_acti_d9c3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='masters_sup_name_4f05c5_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['phone'], name='masters_sup_phone_55652e_idx'),
        ),
    ]
