# Generated by Django 5.0.6 on 2026-05-18 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='branches.branch')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.retailer')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='branches.branch')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.retailer')),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturers', to='branches.branch')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='accounts.retailer')),
            ],
            options={
                'db_table': 'manufacturers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('strength', models.CharField(blank=True, help_text='Example: 500mg, 650mg', max_length=100, null=True)),
                ('units_per_strip', models.PositiveIntegerField(default=1, help_text='Example: 10 tablets in 1 strip')),
                ('loose_sale_allowed', models.BooleanField(default=True)),
                ('prescription_required', models.BooleanField(default=False)),
                ('rack_no', models.CharField(blank=True, max_length=50, null=True)),
                ('minimum_stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='branches.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='masters.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='masters.manufacturer')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.retailer')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('offer_type', models.CharField(choices=[('PRODUCT_DISCOUNT', 'Product Discount'), ('CATEGORY_DISCOUNT', 'Category Discount'), ('BUY_X_GET_Y', 'Buy X Get Y'), ('QUANTITY_DISCOUNT', 'Quantity Discount'), ('FLAT_DISCOUNT', 'Flat Discount'), ('BILL_AMOUNT_DISCOUNT', 'Bill Amount Discount'), ('MANUFACTURER_DISCOUNT', 'Manufacturer Discount'), ('EXPIRY_CLEARANCE', 'Expiry Clearance'), ('FESTIVAL_OFFER', 'Festival Offer'), ('MEMBER_DISCOUNT', 'Member Discount')], max_length=30)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat')], default='PERCENTAGE', max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('flat_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buy_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('free_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry_before_days', models.PositiveIntegerField(blank=True, null=True)),
                ('member_type', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_offers', to='branches.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='masters.category')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='masters.manufacturer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='masters.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_offers', to='accounts.retailer')),
            ],
            options={
                'db_table': 'sales_offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('drug_license_no', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(related_name='suppliers', to='branches.branch')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='accounts.retailer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['retailer'], name='categories_retaile_caeec9_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['branch'], name='categories_branch__52dec9_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='categories_name_98d7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['code'], name='categories_code_a740e7_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='categories_is_acti_aae090_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('retailer', 'code'), ('retailer', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('retailer', 'mobile')},
        ),
        migrations.AddIndex(
            model_name='manufacturer',
            index=models.Index(fields=['retailer'], name='manufacture_retaile_4da02d_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturer',
            index=models.Index(fields=['branch'], name='manufacture_branch__b5655a_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturer',
            index=models.Index(fields=['name'], name='manufacture_name_829e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturer',
            index=models.Index(fields=['is_active'], name='manufacture_is_acti_0eb1e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='manufacturer',
            unique_together={('retailer', 'name')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['retailer'], name='products_retaile_92bead_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_name_6f9890_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('retailer', 'name', 'manufacturer', 'strength')},
        ),
        migrations.AddIndex(
            model_name='salesoffer',
            index=models.Index(fields=['retailer'], name='sales_offer_retaile_add7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='salesoffer',
            index=models.Index(fields=['branch'], name='sales_offer_branch__24a115_idx'),
        ),
        migrations.AddIndex(
            model_name='salesoffer',
            index=models.Index(fields=['offer_type'], name='sales_offer_offer_t_cbde4a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesoffer',
            index=models.Index(fields=['start_date'], name='sales_offer_start_d_244a35_idx'),
        ),
        migrations.AddIndex(
            model_name='salesoffer',
            index=models.Index(fields=['end_date'], name='sales_offer_end_dat_a8f881_idx'),
        ),
        migrations.AddIndex(
            model_name='salesoffer',
            index=models.Index(fields=['is_active'], name='sales_offer_is_acti_0fdfbf_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='masters_sup_name_4f05c5_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['phone'], name='masters_sup_phone_55652e_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['gst_no'], name='masters_sup_gst_no_84f210_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active'], name='masters_sup_is_acti_c5398f_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('retailer', 'phone'), name='unique_supplier_phone_per_retailer'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('retailer', 'gst_no'), name='unique_supplier_gst_per_retailer'),
        ),
    ]
