# Generated by Django 5.0.6 on 2026-05-13 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('offer_type', models.CharField(choices=[('PRODUCT_DISCOUNT', 'Product Discount'), ('CATEGORY_DISCOUNT', 'Category Discount'), ('BUY_X_GET_Y', 'Buy X Get Y'), ('QUANTITY_DISCOUNT', 'Quantity Discount'), ('FLAT_DISCOUNT', 'Flat Discount'), ('BILL_AMOUNT_DISCOUNT', 'Bill Amount Discount'), ('MANUFACTURER_DISCOUNT', 'Manufacturer Discount'), ('EXPIRY_CLEARANCE', 'Expiry Clearance'), ('FESTIVAL_OFFER', 'Festival Offer'), ('MEMBER_DISCOUNT', 'Member Discount')], max_length=30)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat')], default='PERCENTAGE', max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('flat_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buy_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('free_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry_before_days', models.PositiveIntegerField(blank=True, null=True)),
                ('member_type', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='masters.category')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='masters.manufacturer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='masters.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['offer_type'], name='masters_sal_offer_t_b37d24_idx'), models.Index(fields=['start_date'], name='masters_sal_start_d_34670b_idx'), models.Index(fields=['end_date'], name='masters_sal_end_dat_ec3aac_idx'), models.Index(fields=['is_active'], name='masters_sal_is_acti_d9c3b4_idx')],
            },
        ),
    ]
