# Generated by Django 5.0.6 on 2026-05-16 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_retailer_options_and_more'),
        ('branches', '0003_alter_branch_unique_together'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='categories_name_98d7d5_idx',
            old_name='masters_cat_name_8bf495_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='categories_code_a740e7_idx',
            old_name='masters_cat_code_9423e2_idx',
        ),
        migrations.RenameIndex(
            model_name='manufacturer',
            new_name='manufacture_name_829e7d_idx',
            old_name='masters_man_name_db867b_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_name_6f9890_idx',
            old_name='masters_pro_name_7c9c1f_idx',
        ),
        migrations.RenameIndex(
            model_name='salesoffer',
            new_name='sales_offer_offer_t_cbde4a_idx',
            old_name='masters_sal_offer_t_b37d24_idx',
        ),
        migrations.RenameIndex(
            model_name='salesoffer',
            new_name='sales_offer_start_d_244a35_idx',
            old_name='masters_sal_start_d_34670b_idx',
        ),
        migrations.RenameIndex(
            model_name='salesoffer',
            new_name='sales_offer_end_dat_a8f881_idx',
            old_name='masters_sal_end_dat_ec3aac_idx',
        ),
        migrations.RenameIndex(
            model_name='salesoffer',
            new_name='sales_offer_is_acti_0fdfbf_idx',
            old_name='masters_sal_is_acti_d9c3b4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='category',
            name='retailer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.retailer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='customer',
            name='retailer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.retailer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturers', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='retailer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='accounts.retailer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='product',
            name='retailer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.retailer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_offers', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='salesoffer',
            name='retailer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_offers', to='accounts.retailer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='retailer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='accounts.retailer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('retailer', 'code'), ('retailer', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('retailer', 'mobile')},
        ),
        migrations.AlterUniqueTogether(
            name='manufacturer',
            unique_together={('retailer', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('retailer', 'name', 'manufacturer', 'strength')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['retailer'], name='categories_retaile_caeec9_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['branch'], name='categories_branch__52dec9_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='categories_is_acti_aae090_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturer',
            index=models.Index(fields=['retailer'], name='manufacture_retaile_4da02d_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturer',
            index=models.Index(fields=['branch'], name='manufacture_branch__b5655a_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturer',
            index=models.Index(fields=['is_active'], name='manufacture_is_acti_0eb1e2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['retailer'], name='products_retaile_92bead_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesoffer',
            index=models.Index(fields=['retailer'], name='sales_offer_retaile_add7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='salesoffer',
            index=models.Index(fields=['branch'], name='sales_offer_branch__24a115_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['gst_no'], name='masters_sup_gst_no_84f210_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active'], name='masters_sup_is_acti_c5398f_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('retailer', 'phone'), name='unique_supplier_phone_per_retailer'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('retailer', 'gst_no'), name='unique_supplier_gst_per_retailer'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='manufacturer',
            table='manufacturers',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='salesoffer',
            table='sales_offers',
        ),
    ]
