# Generated by Django 5.2.12 on 2026-04-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='masters_cat_name_8bf495_idx'), models.Index(fields=['code'], name='masters_cat_code_9423e2_idx')],
            },
        ),
    ]
