# Generated by Django 5.2.12 on 2026-04-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
        migrations.RenameIndex(
            model_name='productcategory',
            new_name='masters_pro_name_897e66_idx',
            old_name='masters_cat_name_8bf495_idx',
        ),
        migrations.RenameIndex(
            model_name='productcategory',
            new_name='masters_pro_code_23fd83_idx',
            old_name='masters_cat_code_9423e2_idx',
        ),
    ]
