# Generated by Django 5.0.6 on 2026-05-18 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('branches', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='accounts.retailer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PARTIAL', 'Partial'), ('PENDING', 'Pending')], default='RECEIVED', max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.customer')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='accounts.retailer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(default='UNPAID', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.customer')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accounts.retailer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='accounts.retailer')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sales')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('available_qty', models.IntegerField(default=0)),
                ('reserved_qty', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='accounts.retailer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=10)),
                ('adjustment_qty', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='accounts.retailer')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockbatch')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('free_qty', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_return_items', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_return_items', to='accounts.retailer')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.salesreturn')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockbatch')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('free_qty', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_items', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='accounts.retailer')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sales')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockbatch')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('free_qty', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('return_type', models.CharField(choices=[('GOOD', 'Good Stock'), ('DAMAGED', 'Damaged')], default='GOOD', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_return_items', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchasereturn')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_return_items', to='accounts.retailer')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockbatch')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpiryDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('EXPIRY', 'Expired Stock'), ('DAMAGE', 'Damaged Stock')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expiry_damages', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_damages', to='accounts.retailer')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('OPENING', 'Opening Stock'), ('PURCHASE', 'Purchase Entry'), ('PURCHASE_RETURN', 'Purchase Return'), ('SALE', 'Sales Billing'), ('SALES_RETURN', 'Sales Return'), ('ADJUSTMENT_PLUS', 'Stock Adjustment +'), ('ADJUSTMENT_MINUS', 'Stock Adjustment -'), ('EXPIRY', 'Expiry Damage'), ('DAMAGE', 'Damage Stock'), ('TRANSFER_IN', 'Stock Transfer In'), ('TRANSFER_OUT', 'Stock Transfer Out')], max_length=30)),
                ('reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='POSTED', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.customer')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='accounts.retailer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=10)),
                ('qty', models.PositiveIntegerField()),
                ('free_qty', models.PositiveIntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_after', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockbatch')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transaction_items', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transaction_items', to='accounts.retailer')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransaction')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockbatch')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_out', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='accounts.retailer')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_in', to='branches.branch')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial Paid'), ('UNPAID', 'Unpaid')], default='PAID', max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.retailer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_no'], name='inventory_p_payment_98c2ef_idx'), models.Index(fields=['retailer'], name='inventory_p_retaile_3f02ec_idx'), models.Index(fields=['branch'], name='inventory_p_branch__97226d_idx'), models.Index(fields=['supplier'], name='inventory_p_supplie_c653ae_idx'), models.Index(fields=['status'], name='inventory_p_status_4659b1_idx'), models.Index(fields=['created_at'], name='inventory_p_created_0bd134_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['return_no'], name='inventory_p_return__91a3d7_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['retailer'], name='inventory_p_retaile_c0caa5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['branch'], name='inventory_p_branch__39e7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['supplier'], name='inventory_p_supplie_9685ef_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['status'], name='inventory_p_status_a83a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['created_at'], name='inventory_p_created_3a2cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_no'], name='inventory_r_receipt_7cd1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['retailer'], name='inventory_r_retaile_e5ac97_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['branch'], name='inventory_r_branch__4bd47b_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['customer'], name='inventory_r_custome_407ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status'], name='inventory_r_status_7edf07_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['created_at'], name='inventory_r_created_ecdece_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['invoice_no'], name='inventory_s_invoice_4d1562_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['retailer'], name='inventory_s_retaile_a9627f_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['branch'], name='inventory_s_branch__dd9948_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['customer'], name='inventory_s_custome_9412ab_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['payment_status'], name='inventory_s_payment_090415_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['status'], name='inventory_s_status_aceae1_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['created_at'], name='inventory_s_created_442f92_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['return_no'], name='inventory_s_return__87ba54_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['status'], name='inventory_s_status_5f41de_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['created_at'], name='inventory_s_created_d00642_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['retailer'], name='inventory_s_retaile_1076a8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['branch'], name='inventory_s_branch__2d30b7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['product'], name='inventory_s_product_a78359_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['supplier'], name='inventory_s_supplie_a575a6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['batch_no'], name='inventory_s_batch_n_c1aa5e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['expiry_date'], name='inventory_s_expiry__709598_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['is_expired'], name='inventory_s_is_expi_84602d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockbatch',
            unique_together={('product', 'batch_no', 'branch')},
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['retailer'], name='inventory_s_retaile_4cb601_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['branch'], name='inventory_s_branch__b30b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['product'], name='inventory_s_product_bb1a16_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['batch'], name='inventory_s_batch_i_40bf21_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['adjustment_type'], name='inventory_s_adjustm_d014d9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['created_at'], name='inventory_s_created_8901aa_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['retailer'], name='inventory_s_retaile_37b894_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['branch'], name='inventory_s_branch__4512fc_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['product'], name='inventory_s_product_e1829a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['batch'], name='inventory_s_batch_i_a0cfb1_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['created_at'], name='inventory_s_created_3b1ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='salesitem',
            index=models.Index(fields=['retailer'], name='inventory_s_retaile_0b914d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesitem',
            index=models.Index(fields=['branch'], name='inventory_s_branch__3d23a9_idx'),
        ),
        migrations.AddIndex(
            model_name='salesitem',
            index=models.Index(fields=['sales'], name='inventory_s_sales_i_d40291_idx'),
        ),
        migrations.AddIndex(
            model_name='salesitem',
            index=models.Index(fields=['product'], name='inventory_s_product_f80a84_idx'),
        ),
        migrations.AddIndex(
            model_name='salesitem',
            index=models.Index(fields=['batch'], name='inventory_s_batch_i_78bc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesitem',
            index=models.Index(fields=['created_at'], name='inventory_s_created_c32766_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnitem',
            index=models.Index(fields=['retailer'], name='inventory_p_retaile_a8960f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnitem',
            index=models.Index(fields=['branch'], name='inventory_p_branch__0c2f87_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnitem',
            index=models.Index(fields=['product'], name='inventory_p_product_2c10da_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnitem',
            index=models.Index(fields=['batch'], name='inventory_p_batch_i_d0d754_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnitem',
            index=models.Index(fields=['return_type'], name='inventory_p_return__6e54cd_idx'),
        ),
        migrations.AddIndex(
            model_name='expirydamage',
            index=models.Index(fields=['retailer'], name='inventory_e_retaile_94a41a_idx'),
        ),
        migrations.AddIndex(
            model_name='expirydamage',
            index=models.Index(fields=['branch'], name='inventory_e_branch__abd04d_idx'),
        ),
        migrations.AddIndex(
            model_name='expirydamage',
            index=models.Index(fields=['issue_type'], name='inventory_e_issue_t_5052a9_idx'),
        ),
        migrations.AddIndex(
            model_name='expirydamage',
            index=models.Index(fields=['expiry_date'], name='inventory_e_expiry__930497_idx'),
        ),
        migrations.AddIndex(
            model_name='expirydamage',
            index=models.Index(fields=['created_at'], name='inventory_e_created_240974_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_no'], name='inventory_s_transac_840c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type'], name='inventory_s_transac_f888de_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['status'], name='inventory_s_status_5b4751_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['retailer'], name='inventory_s_retaile_46c368_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['branch'], name='inventory_s_branch__2c752b_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['created_at'], name='inventory_s_created_ff5dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransactionitem',
            index=models.Index(fields=['retailer'], name='inventory_s_retaile_95af3f_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransactionitem',
            index=models.Index(fields=['branch'], name='inventory_s_branch__10af7e_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransactionitem',
            index=models.Index(fields=['transaction'], name='inventory_s_transac_329f49_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransactionitem',
            index=models.Index(fields=['product'], name='inventory_s_product_4a4810_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransactionitem',
            index=models.Index(fields=['batch'], name='inventory_s_batch_i_160634_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransactionitem',
            index=models.Index(fields=['movement_type'], name='inventory_s_movemen_ccbda3_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransactionitem',
            index=models.Index(fields=['created_at'], name='inventory_s_created_f42f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['transfer_no'], name='inventory_s_transfe_19fdb6_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['retailer'], name='inventory_s_retaile_e88eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['from_branch'], name='inventory_s_from_br_e44f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['to_branch'], name='inventory_s_to_bran_5ff1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['product'], name='inventory_s_product_5b102b_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['status'], name='inventory_s_status_8e22d4_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['created_at'], name='inventory_s_created_99002d_idx'),
        ),
    ]
