# Generated by Django 5.0.6 on 2026-05-25 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auditlog_accounts_au_timesta_276167_idx_and_more"),
        ("branches", "0003_branch_branches_br_retaile_5e3433_idx_and_more"),
        ("inventory", "0001_initial"),
        ("masters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasereturn",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchasereturn",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sales",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sales",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="expirydamage",
            index=models.Index(
                fields=["retailer", "branch"], name="inventory_e_retaile_367972_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expirydamage",
            index=models.Index(
                fields=["retailer", "issue_type"], name="inventory_e_retaile_0ba81a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expirydamage",
            index=models.Index(
                fields=["retailer", "expiry_date"],
                name="inventory_e_retaile_6a2bc4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expirydamage",
            index=models.Index(
                fields=["branch", "issue_type"], name="inventory_e_branch__dadf4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["retailer", "branch"], name="inventory_p_retaile_091179_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["retailer", "supplier"], name="inventory_p_retaile_112d72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["retailer", "status"], name="inventory_p_retaile_816476_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["branch", "status"], name="inventory_p_branch__3413ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["supplier", "status"], name="inventory_p_supplie_70b8c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereturn",
            index=models.Index(
                fields=["retailer", "branch"], name="inventory_p_retaile_6b2095_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereturn",
            index=models.Index(
                fields=["retailer", "supplier"], name="inventory_p_retaile_c018d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereturn",
            index=models.Index(
                fields=["retailer", "status"], name="inventory_p_retaile_925b21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereturn",
            index=models.Index(
                fields=["branch", "status"], name="inventory_p_branch__8502a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereturn",
            index=models.Index(
                fields=["supplier", "status"], name="inventory_p_supplie_ed54a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereturnitem",
            index=models.Index(
                fields=["created_at"], name="inventory_p_created_42147b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereturnitem",
            index=models.Index(
                fields=["retailer", "branch"], name="inventory_p_retaile_d88ceb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereturnitem",
            index=models.Index(
                fields=["retailer", "product"], name="inventory_p_retaile_d90656_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereturnitem",
            index=models.Index(
                fields=["branch", "product"], name="inventory_p_branch__3e4cd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereturnitem",
            index=models.Index(
                fields=["product", "batch"], name="inventory_p_product_bb309c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereturnitem",
            index=models.Index(
                fields=["retailer", "return_type"],
                name="inventory_p_retaile_cdd84a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["retailer", "branch"], name="inventory_r_retaile_c74bc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["retailer", "customer"], name="inventory_r_retaile_e5427c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["retailer", "status"], name="inventory_r_retaile_8d3643_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["branch", "status"], name="inventory_r_branch__5a4107_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["customer", "status"], name="inventory_r_custome_2be1ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sales",
            index=models.Index(
                fields=["retailer", "branch"], name="inventory_s_retaile_4a0748_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sales",
            index=models.Index(
                fields=["retailer", "customer"], name="inventory_s_retaile_17bc98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sales",
            index=models.Index(
                fields=["retailer", "payment_status"],
                name="inventory_s_retaile_3e958d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sales",
            index=models.Index(
                fields=["retailer", "status"], name="inventory_s_retaile_7be022_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sales",
            index=models.Index(
                fields=["branch", "status"], name="inventory_s_branch__2c148f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sales",
            index=models.Index(
                fields=["customer", "payment_status"],
                name="inventory_s_custome_aac42f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sales",
            index=models.Index(
                fields=["created_at", "status"], name="inventory_s_created_6b0d77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesitem",
            index=models.Index(
                fields=["retailer", "branch"], name="inventory_s_retaile_cb0425_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesitem",
            index=models.Index(
                fields=["retailer", "sales"], name="inventory_s_retaile_2d66ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesitem",
            index=models.Index(
                fields=["retailer", "product"], name="inventory_s_retaile_28a6ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesitem",
            index=models.Index(
                fields=["branch", "product"], name="inventory_s_branch__0894c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesitem",
            index=models.Index(
                fields=["sales", "product"], name="inventory_s_sales_i_7a61df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesitem",
            index=models.Index(
                fields=["product", "batch"], name="inventory_s_product_cb053b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreturn",
            index=models.Index(
                fields=["retailer"], name="inventory_s_retaile_3313c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreturn",
            index=models.Index(
                fields=["branch"], name="inventory_s_branch__d8643d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreturn",
            index=models.Index(fields=["sales"], name="inventory_s_sales_i_881cbb_idx"),
        ),
        migrations.AddIndex(
            model_name="salesreturn",
            index=models.Index(
                fields=["retailer", "branch"], name="inventory_s_retaile_8c0b84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreturn",
            index=models.Index(
                fields=["retailer", "status"], name="inventory_s_retaile_c3079b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreturn",
            index=models.Index(
                fields=["branch", "status"], name="inventory_s_branch__8f4a04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreturn",
            index=models.Index(
                fields=["sales", "status"], name="inventory_s_sales_i_84906e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreturn",
            index=models.Index(
                fields=["created_at", "status"], name="inventory_s_created_8e8ef4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreturnitem",
            index=models.Index(
                fields=["retailer", "branch"], name="inventory_s_retaile_b1efd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreturnitem",
            index=models.Index(
                fields=["retailer", "product"], name="inventory_s_retaile_d432d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreturnitem",
            index=models.Index(
                fields=["branch", "product"], name="inventory_s_branch__ad6177_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreturnitem",
            index=models.Index(
                fields=["sales_return"], name="inventory_s_sales_r_c6cc9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesreturnitem",
            index=models.Index(
                fields=["sales_return", "product"],
                name="inventory_s_sales_r_3831ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesreturnitem",
            index=models.Index(
                fields=["product", "batch"], name="inventory_s_product_c49de2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["retailer", "branch"], name="inventory_s_retaile_eb1e5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["retailer", "product"], name="inventory_s_retaile_a6e9c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["branch", "product"], name="inventory_s_branch__a163fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["product", "batch"], name="inventory_s_product_7d5953_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["retailer", "adjustment_type"],
                name="inventory_s_retaile_053ebe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["branch", "adjustment_type"],
                name="inventory_s_branch__052d45_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockadjustment",
            index=models.Index(
                fields=["created_at", "adjustment_type"],
                name="inventory_s_created_d06af9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["retailer", "branch"], name="inventory_s_retaile_f44d2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["retailer", "product"], name="inventory_s_retaile_364f35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["branch", "product"], name="inventory_s_branch__06ae25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["product", "batch_no"], name="inventory_s_product_c6a111_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["product", "expiry_date"], name="inventory_s_product_cc8bb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["branch", "expiry_date"], name="inventory_s_branch__aa2d5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["available_qty"], name="inventory_s_availab_22d931_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["available_qty", "expiry_date"],
                name="inventory_s_availab_896a21_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["product", "available_qty"],
                name="inventory_s_product_be7612_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["product", "is_expired"], name="inventory_s_product_c73104_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["retailer", "branch"], name="inventory_s_retaile_84fe1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["retailer", "transaction_type"],
                name="inventory_s_retaile_7ec309_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["retailer", "status"], name="inventory_s_retaile_299518_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["branch", "status"], name="inventory_s_branch__991406_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["transaction_type", "status"],
                name="inventory_s_transac_ed2a7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["supplier"], name="inventory_s_supplie_caa2fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["customer"], name="inventory_s_custome_aecbe6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["reference_no"], name="inventory_s_referen_992e42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransactionitem",
            index=models.Index(
                fields=["retailer", "branch"], name="inventory_s_retaile_f0c8f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransactionitem",
            index=models.Index(
                fields=["retailer", "product"], name="inventory_s_retaile_b1b1b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransactionitem",
            index=models.Index(
                fields=["branch", "product"], name="inventory_s_branch__95b6f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransactionitem",
            index=models.Index(
                fields=["product", "batch"], name="inventory_s_product_ed2e9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransactionitem",
            index=models.Index(
                fields=["product", "movement_type"],
                name="inventory_s_product_44f837_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransactionitem",
            index=models.Index(
                fields=["batch", "movement_type"], name="inventory_s_batch_i_efa67f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransactionitem",
            index=models.Index(
                fields=["transaction", "movement_type"],
                name="inventory_s_transac_281a18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransactionitem",
            index=models.Index(
                fields=["created_at", "movement_type"],
                name="inventory_s_created_8945fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransactionitem",
            index=models.Index(
                fields=["expiry_date"], name="inventory_s_expiry__af820b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["branch"], name="inventory_s_branch__30b682_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["batch"], name="inventory_s_batch_i_606eed_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["retailer", "status"], name="inventory_s_retaile_52b300_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["from_branch", "status"], name="inventory_s_from_br_723b34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["to_branch", "status"], name="inventory_s_to_bran_f94e7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["from_branch", "to_branch"],
                name="inventory_s_from_br_7e1097_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["product", "batch"], name="inventory_s_product_47e441_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["retailer", "product"], name="inventory_s_retaile_c78f09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["created_at", "status"], name="inventory_s_created_7b61f4_idx"
            ),
        ),
    ]
