# Generated by Django 5.0.6 on 2026-05-15 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_retailer_alter_user_options_loginlog_branch_and_more'),
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.retailer'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['retailer'], name='branches_br_retaile_b3b503_idx'),
        ),
    ]
