# Generated by Django 5.0.6 on 2026-05-25 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auditlog_accounts_au_timesta_276167_idx_and_more"),
        ("branches", "0002_branch_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["retailer", "is_active"], name="branches_br_retaile_5e3433_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["retailer", "name"], name="branches_br_retaile_3aaac4_idx"
            ),
        ),
    ]
