# Generated by Django 5.0.6 on 2026-05-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_retailer_options_and_more'),
        ('branches', '0002_branch_retailer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('retailer', 'name')},
        ),
    ]
