# Generated by Django 5.0.6 on 2026-06-10 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_retailer_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('restored', 'Restored')], default='success', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='accounts.retailer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['retailer'], name='backups_bac_retaile_ae9a43_idx'), models.Index(fields=['backup_type'], name='backups_bac_backup__75fe39_idx'), models.Index(fields=['status'], name='backups_bac_status_fc8901_idx'), models.Index(fields=['created_at'], name='backups_bac_created_ac95aa_idx'), models.Index(fields=['retailer', 'created_at'], name='backups_bac_retaile_6ab7ee_idx')],
            },
        ),
    ]
