# Generated by Django 5.0.6 on 2026-06-13 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_retailer_is_deleted'),
        ('backups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('backup_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='backuplog',
            name='backup_scope',
            field=models.CharField(choices=[('database', 'Database'), ('media', 'Media'), ('full', 'Full')], default='database', max_length=20),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='checksum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['backup_scope'], name='backups_bac_backup__1c120e_idx'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='retailer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedule', to='accounts.retailer'),
        ),
        migrations.AddIndex(
            model_name='backupschedule',
            index=models.Index(fields=['retailer'], name='backups_bac_retaile_0ef3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='backupschedule',
            index=models.Index(fields=['frequency'], name='backups_bac_frequen_17cc7b_idx'),
        ),
        migrations.AddIndex(
            model_name='backupschedule',
            index=models.Index(fields=['is_active'], name='backups_bac_is_acti_8cbe80_idx'),
        ),
        migrations.AddIndex(
            model_name='backupschedule',
            index=models.Index(fields=['backup_time'], name='backups_bac_backup__6440ac_idx'),
        ),
        migrations.AddIndex(
            model_name='backupschedule',
            index=models.Index(fields=['created_at'], name='backups_bac_created_897f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='backupschedule',
            index=models.Index(fields=['frequency', 'is_active'], name='backups_bac_frequen_4c9a6c_idx'),
        ),
    ]
